AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless PySpark
Parameters:
  AccessKey:
    Type: String
    Description: AWS Access Key
  SecretKey:
    Type: String
    Description: AWS Secret Key
  LogLevel:
    Type: String
    Description: INFO, DEBUG, ERROR or WARNING
    Default: INFO
Globals:
  Function:
    MemorySize: 512
    Timeout: 900
    Tags:
      AppName: pyspark
Resources:
  SparkRuntime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: spark-runtime
      Description: Spark Runtime
      ContentUri: s3://didone-spark/spark.zip
      CompatibleRuntimes:
      - provided
      RetentionPolicy: Delete
  SparkDrivers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: spark-drivers
      Description: Spark Extra Drivers
      ContentUri: s3://didone-spark/drivers.zip
      CompatibleRuntimes:
      - provided
      RetentionPolicy: Delete
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Hello World with spark context
      CodeUri: s3://didone-spark-sam/fe8a836aaf5858cbe447c89b52c8a3f1
      Handler: job.run
      Runtime: provided
      Layers:
      - Ref: SparkRuntime
      - Ref: SparkDrivers
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          LOG_LEVEL:
            Ref: LogLevel
  PaisesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Read Files from S3 bucket
      CodeUri: s3://didone-spark-sam/c1219daa3f3b05ebf26dc0bc6637b709
      Handler: job.run
      Runtime: provided
      Layers:
      - Ref: SparkRuntime
      - Ref: SparkDrivers
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonS3FullAccess
      Environment:
        Variables:
          LOG_LEVEL:
            Ref: LogLevel
          ACCESS_KEY:
            Ref: AccessKey
          SECRET_KEY:
            Ref: SecretKey
